name: Call Software Dependency Workflow

on:
  push: 
    branches:
      - main

jobs:
  call-software-dependency-workflow:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/sbom.yaml@main
    permissions: # Required if the admin repo is private
      contents: read
      id-token: write
      
