name: Call Dependency Workflow

on:
  push:
    branches:
      - main

jobs:
  call-dependency-workflow:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/dependency-workflow.yaml@main
    permissions:
      contents: read
    with:
      DEPENDENCY_TRACK_API_KEY: ${{ secret.DEPENDENCY_TRACK_API_KEY }}
      ADMIN_ACCESS_TOKEN: ${{ secret.ADMIN_ACCESS_TOKEN }}
