name: Call Software Dependency Workflow

on:
  push: 
    branches:
      - main

jobs:
  call-software-dependency-workflow:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/dependency-workflow.yaml@main
    permissions: # Required if the admin repo is private
      contents: read
      id-token: write
    with:
      secrets.DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
      secrets.ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
