name: New Threat workflow

on:
  workflow_dispatch:
    inputs:
      cveNumber:
        description: 'CVE to test for'
        required: false
        default: 'null'
      vulnerablePackage:
        description: 'Packages affected by CVE'
        required: true
        default: 'null'
      packageVersions:
        description: 'Versions affected by CVE'
        required: true
        default: 'null'

jobs:
  new-threats:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/new-threats.yaml@main
    with:
      cveNumber: ${{ inputs.cveNumber }}
      vulnerablePackage: ${{ inputs.vulnerablePackage }}
      packageVersions: ${{ inputs.packageVersions }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
